### ISSUE TITLE
DBMS

### ISSUE THREAD

**Issue by Omar-Karimov** [Omar-Karimov/SQL_Project#1]
![dbms](https://user-images.githubusercontent.com/68358028/89329735-e21a4680-d697-11ea-8cf1-69538006d418.png)

**Comment by utkarshverma11** [comment]
what needs to be done in this .?

**Comment by Omar-Karimov** [comment]
You need to create RDBMS for the Getbus24 intercity bus company. 
For a more detailed explanation of the task, you can check README.
